version: '3'
services:
  jdou:
    image: jdou:v1.1
    container_name: jdou
    ports:
      - 8080:8080
    environment:
      START_FROM_DOCKER: true
      FILE_PATH: /Users/yuyunlong/opt/jd_cookie.txt
#      PT_PIN: '你的pt_pin'
#      PT_KEY: '你的pt_key'
